# Generated by Django 4.2.6 on 2023-10-26 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="senior",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="senior_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
