# Generated by Django 4.2.6 on 2023-10-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=255)),
                ("issue_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="role",
            name="value",
            field=models.CharField(max_length=15),
        ),
    ]
