# Generated by Django 4.2.6 on 2023-10-26 18:42

from django.db import migrations, models

import users.constants


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("AD", "AD"), ("SR", "SR"), ("JR", "JR")],
                default=users.constants.Role["JUNIOR"],
                max_length=2,
            ),
        ),
    ]
