# Generated by Django 4.2.6 on 2023-10-13 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_message_alter_role_value"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issues",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
